# Generated by Django 4.2.13 on 2024-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Partner site URL'),
        ),
    ]
