# Generated by Django 4.2.13 on 2024-05-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
                ('surname', models.CharField(max_length=55, verbose_name='Surname')),
                ('nationality', models.CharField(max_length=55, verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title of Event')),
                ('country', models.CharField(max_length=55, verbose_name='Country of Event')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('image_of_track', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image of track')),
                ('documents', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Any documents')),
                ('date_of_start', models.DateField(verbose_name='Date of start')),
                ('date_from', models.DateField(verbose_name='Date from')),
                ('date_to', models.DateField(verbose_name='Date to')),
                ('players', models.ManyToManyField(related_name='events', to='main.player', verbose_name='Players who participate in the event')),
            ],
        ),
    ]
