# Generated by Django 4.2.13 on 2024-06-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
