# Generated by Django 4.2.13 on 2024-06-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery_alter_event_image_of_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/Event/logo', verbose_name='Logo of event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_start',
            field=models.DateTimeField(verbose_name='Date of start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=155, verbose_name='Title of Event'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(db_index=True, max_length=55, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, max_length=55, verbose_name='Name'),
        ),
    ]
