# Generated by Django 4.2.13 on 2024-06-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_statistics_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
