# Generated by Django 4.2.13 on 2024-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_gallery_delete_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_to',
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_end',
            field=models.DateField(null=True, verbose_name='Date of end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_start',
            field=models.DateTimeField(null=True, verbose_name='Date of start'),
        ),
    ]
