# Generated by Django 4.2.13 on 2024-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_event_date_from_remove_event_date_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistics', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterField(
            model_name='event',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='files/events/', verbose_name='Any documents'),
        ),
    ]
