# Generated by Django 4.2.13 on 2024-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_options_alter_statistics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(upload_to='images/Event/logo', verbose_name='Logo of event'),
        ),
    ]
