# Generated by Django 4.2.13 on 2024-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_options_alter_statistics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=55, verbose_name='Track')),
                ('image', models.ImageField(upload_to='images/tracks', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/Event/logo', verbose_name='Logo of event'),
        ),
    ]
