# Generated by Django 4.2.13 on 2024-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_event_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/Event/logo', verbose_name='Logo of event'),
        ),
    ]
