# Generated by Django 4.2.13 on 2024-07-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_event_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(verbose_name='Lap Number')),
                ('lap_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lap Time')),
                ('sector1_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sector 1 Time')),
                ('sector2_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sector 2 Time')),
                ('sector3_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sector 3 Time')),
                ('sector4_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sector 4 Time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_statistics', to='main.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='main.player')),
            ],
            options={
                'verbose_name': 'Player Statistic',
                'verbose_name_plural': 'Player Statistics',
                'unique_together': {('player', 'event', 'lap_number')},
            },
        ),
    ]
