# Generated by Django 4.2.13 on 2024-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=55, verbose_name='Track')),
                ('image', models.ImageField(upload_to='images/tracks', verbose_name='Image')),
            ],
        ),
    ]
