# Generated by Django 4.2.13 on 2024-06-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=55, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=355, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/gallery', verbose_name='Logo')),
            ],
        ),
    ]
